# -*- coding: utf-8 -*-
"""Roni Merdiansah_Proyek Kedua : Membuat Model Machine Learning dengan Data Time Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14nwM_QExIMAJvv4bhF_rkRXUi8dOSaMN

Link Dataset

-https://www.kaggle.com/datasets/balabaskar/silver-prices-1968-2021
"""

import numpy as np
import pandas as pd
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

data_train = pd.read_csv('drive/MyDrive/Dicoding/BPML/Submission 2/LBMA-SILVER.csv')
data_train.info()

data_train

data_train.isnull().sum()

del data_train['EURO']
data_train = data_train.dropna()
data_train.isnull().sum()

df_plot = data_train
df_plot[df_plot.columns.to_list()].plot(subplots=True, figsize=(20, 15))
plt.show()

dates = data_train['Date'].values
usd = data_train['USD'].values

dates = np.array(dates)
usd = np.array(usd)

plt.figure(figsize=(20,5))
plt.plot(dates, usd)

plt.title('Silver price in USD currency in a Day', fontsize = 30)
plt.ylabel('Temperature', fontsize = 20)
plt.xlabel('Datetime', fontsize = 20)

data_train.dtypes

data_train['Date'] = pd.to_datetime(data_train['Date'])
data_train = data_train.set_index('Date')

data_by_month = data_train.resample('A').mean()

time = data_by_month.index.values
test = data_by_month['USD'].values

plt.figure(figsize=(20,5))
plt.plot(time, test)
plt.title('Average Silver price in USD currency in a Year', fontsize = 30)
plt.ylabel('Value', fontsize = 20)
plt.xlabel('Year', fontsize = 20)
plt.grid(color='grey')

usd = np.array(data_train['USD'])
usd = usd.reshape(-1, 1)

scaler = MinMaxScaler()
usd = scaler.fit_transform(usd)

usd_train, usd_valid, dates_train, dates_valid = train_test_split(usd, dates, train_size=0.8, test_size = 0.2, shuffle = False )

print('Total Data Train : ',len(usd_train))
print('Total Data Validation : ',len(dates_valid))

def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
  series = tf.expand_dims(series, axis=-1)
  ds = tf.data.Dataset.from_tensor_slices(series)
  ds = ds.window(window_size + 1, shift=1, drop_remainder = True)
  ds = ds.flat_map(lambda w: w.batch(window_size + 1))
  ds = ds.shuffle(shuffle_buffer)
  ds = ds.map(lambda w: (w[:-1], w[-1:]))
  return ds.batch(batch_size).prefetch(1)

train_set = windowed_dataset(usd_train, window_size=64, batch_size=200, shuffle_buffer=1000)
val_set = windowed_dataset(usd_valid, window_size=64, batch_size=200, shuffle_buffer=1000)

model = tf.keras.models.Sequential([
  tf.keras.layers.LSTM(128, return_sequences=True, input_shape=[None, 1]),
  tf.keras.layers.LSTM(128),
  tf.keras.layers.Dense(32, activation="relu"),
  tf.keras.layers.Dense(16, activation="relu"),
  tf.keras.layers.Dense(1),
])

threshold_mae = (usd.max() - usd.min()) * 10/100
print(threshold_mae)

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('mae') < threshold_mae and logs.get('val_mae') < threshold_mae):
      print("\nMAE dari model < 10% skala data")
      self.model.stop_training = True
callbacks = myCallback()

optimizer = tf.keras.optimizers.SGD(lr=1.0000e-04, momentum=0.9)

model.compile(loss=tf.keras.losses.Huber(),
              optimizer=optimizer,
              metrics=["mae"])

history = model.fit(train_set, epochs=300, validation_data = val_set, callbacks=[callbacks])

plt.figure(figsize=(20,5))
plt.plot(history.history['mae'])
plt.plot(history.history['val_mae'])
plt.title('Model MAE', fontsize=30)
plt.ylabel('MAE', fontsize=20)
plt.xlabel('epoch', fontsize=20)
plt.legend(['train', 'test'], loc='upper left')
plt.show()

plt.figure(figsize=(20,5))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss', fontsize=30)
plt.ylabel('Loss', fontsize=20)
plt.xlabel('epoch', fontsize=20)
plt.legend(['train', 'test'], loc='upper left')
plt.show()